export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_PENNDING = "LOGIN_PENNDING";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const ADD_STUDENT_SUCCESS = "ADD_STUDENT_SUCCESS";
export const ADD_STUDENT_PENNDING = "ADD_STUDENT_PENNDING";
export const ADD_STUDENT_FAIL = "ADD_STUDENT_FAIL";

    